framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: common
                        type: topic
                    queues:
                      {{ skeleton_name }}:
                            binding_keys:
                                - event.broadcast

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
